# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be43d6539a171b519f1e2d8766f5f5f66fac24c3a83f93b77bf079cfd7e67a237a508dcbc3b04e386b731cec50da3578b8cd50da25a1ae9be40d3363e09ef34

test:
  secret_key_base: 7d567a9826c58680eb97499f36adbed801946c2d55d916bfdbdba65ffd7e772117588e437a2d3795b59ad29c09217cbf4abc0c2ed01eeeb8fefd0a43116cd69b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
